### ISSUE TITLE
Add instructions for setting up unixodbc / FreeTDS

### ISSUE THREAD

**Issue by dlo** [lionheart/django-pyodbc#10]

**Comment by sarahlunette** [comment]
Hello - it works fine till I import pyodbc - I have an import error. Before that even, osql commands do not work and I was able to make pyodbc import before but still got an error [iOBDC] instead of [unixODBC]

**Comment by WilliamQLiu** [comment]
Maybe you can try pymssql instead of pyodbc.  I had this as a stackoverflow
answer at
http://stackoverflow.com/questions/11678696/sql-server-python-and-os-x/27239553#27239553
and that's what someone recommended.

**Comment by sarahlunette** [comment]
Thanks ... Unfortunately I had already done that and it still did not work. It clearly is the connection between pyodbc and unixodbc .. either where the files are located or juste the script for pyodbc setup needs more changes ... Any clue ? thanks a lot
