### ISSUE TITLE
django 1.8 patch

### ISSUE THREAD

**Issue by wgbbiao** [lionheart/django-pyodbc#104]
diff --git a/django_pyodbc/base.py b/django_pyodbc/base.py
index f467417..02f8ee5 100644
--- a/django_pyodbc/base.py
+++ b/django_pyodbc/base.py
@@ -60,6 +60,17 @@ from django_pyodbc.introspection import DatabaseIntrospection
 DatabaseError = Database.Error
 IntegrityError = Database.IntegrityError
 
+class DataTypesWrapper(dict):
+    def __getitem__(self, item):
+        if item in ('PositiveIntegerField', 'PositiveSmallIntegerField'):
+            # The check name must be unique for the database. Add a random
+            # component so the regresion tests don't complain about duplicate names
+            fldtype = {'PositiveIntegerField': 'int', 'PositiveSmallIntegerField': 'smallint'}[item]
+            rnd_hash = md5_constructor(b(str(random.random()))).hexdigest()
+            unique = base64.b64encode(b(rnd_hash), b('__'))[:6]
+            return '%(fldtype)s CONSTRAINT [CK_%(fldtype)s_pos_%(unique)s_%%(column)s] CHECK ([%%(column)s] >= 0)' % locals()
+        return super(DataTypesWrapper, self).__getitem__(item)
+
 class DatabaseFeatures(BaseDatabaseFeatures):
     can_use_chunked_reads = False
     can_return_id_from_insert = True
@@ -94,6 +105,42 @@ class DatabaseWrapper(BaseDatabaseWrapper):
     Database = Database
     limit_table_list = False
 
+# Any format strings starting with "qn_" are quoted before being used in the
+    # output (the "qn_" prefix is stripped before the lookup is performed.
+
+    data_types = DataTypesWrapper({
+        'AutoField':                    'int IDENTITY (1, 1)',
+        'BigAutoField':                 'bigint IDENTITY (1, 1)',
+        'BigIntegerField':              'bigint',
+        'BinaryField':                  'varbinary(max)',
+        'BooleanField':                 'bit',
+        'CharField':                    'nvarchar(%(max_length)s)',
+        'CommaSeparatedIntegerField':   'nvarchar(%(max_length)s)',
+        'DateField':                    'date',
+        'DateTimeField':                'datetime',
+        'DateTimeOffsetField':          'datetimeoffset',
+        'DecimalField':                 'decimal(%(max_digits)s, %(decimal_places)s)',
+        'FileField':                    'nvarchar(%(max_length)s)',
+        'FilePathField':                'nvarchar(%(max_length)s)',
+        'FloatField':                   'double precision',
+        'GenericIPAddressField':        'nvarchar(39)',
+        'IntegerField':                 'int',
+        'IPAddressField':               'nvarchar(15)',
+        'LegacyDateField':              'datetime',
+        'LegacyDateTimeField':          'datetime',
+        'LegacyTimeField':              'time',
+        'NewDateField':                 'date',
+        'NewDateTimeField':             'datetime2',
+        'NewTimeField':                 'time',
+        'NullBooleanField':             'bit',
+        'OneToOneField':                'int',
+        'PositiveIntegerField':         'int CHECK ([%(column)s] >= 0)',
+        'PositiveSmallIntegerField':    'smallint CHECK ([%(column)s] >= 0)',
+        'SlugField':                    'nvarchar(%(max_length)s)',
+        'SmallIntegerField':            'smallint',
+        'TextField':                    'nvarchar(max)',
+        'TimeField':                    'time',        
+    })
     # Collations:       http://msdn2.microsoft.com/en-us/library/ms184391.aspx
     #                   http://msdn2.microsoft.com/en-us/library/ms179886.aspx
     # T-SQL LIKE:       http://msdn2.microsoft.com/en-us/library/ms179859.aspx
diff --git a/django_pyodbc/compiler.py b/django_pyodbc/compiler.py
index 1d18aea..1d64d64 100644
--- a/django_pyodbc/compiler.py
+++ b/django_pyodbc/compiler.py
@@ -115,21 +115,21 @@ class SQLCompiler(compiler.SQLCompiler):
         E.g. AVG([1, 2]) needs to yield 1.5, not 1
         """
         for alias, aggregate in self.query.aggregate_select.items():
-            if aggregate.sql_function == 'AVG':# and self.connection.cast_avg_to_float:
+            if aggregate.function == 'AVG':# and self.connection.cast_avg_to_float:
                 # Embed the CAST in the template on this query to
                 # maintain multi-db support.
                 self.query.aggregate_select[alias].sql_template = \
                     '%(function)s(CAST(%(field)s AS FLOAT))'
             # translate StdDev function names
-            elif aggregate.sql_function == 'STDDEV_SAMP':
-                self.query.aggregate_select[alias].sql_function = 'STDEV'
-            elif aggregate.sql_function == 'STDDEV_POP':
-                self.query.aggregate_select[alias].sql_function = 'STDEVP'
+            elif aggregate.function == 'STDDEV_SAMP':
+                self.query.aggregate_select[alias].function = 'STDEV'
+            elif aggregate.function == 'STDDEV_POP':
+                self.query.aggregate_select[alias].function = 'STDEVP'
             # translate Variance function names
-            elif aggregate.sql_function == 'VAR_SAMP':
-                self.query.aggregate_select[alias].sql_function = 'VAR'
-            elif aggregate.sql_function == 'VAR_POP':
-                self.query.aggregate_select[alias].sql_function = 'VARP'
+            elif aggregate.function == 'VAR_SAMP':
+                self.query.aggregate_select[alias].function = 'VAR'
+            elif aggregate.function == 'VAR_POP':
+                self.query.aggregate_select[alias].function = 'VARP'
 
     def as_sql(self, with_limits=True, with_col_aliases=False):
         # Django #12192 - Don't execute any DB query when QS slicing results in limit 0
diff --git a/django_pyodbc/creation.py b/django_pyodbc/creation.py
index 86d7d3c..c4d28ed 100644
--- a/django_pyodbc/creation.py
+++ b/django_pyodbc/creation.py
@@ -10,59 +10,13 @@ except ImportError:
 
 from django_pyodbc.compat import b, md5_constructor
 
-class DataTypesWrapper(dict):
-    def __getitem__(self, item):
-        if item in ('PositiveIntegerField', 'PositiveSmallIntegerField'):
-            # The check name must be unique for the database. Add a random
-            # component so the regresion tests don't complain about duplicate names
-            fldtype = {'PositiveIntegerField': 'int', 'PositiveSmallIntegerField': 'smallint'}[item]
-            rnd_hash = md5_constructor(b(str(random.random()))).hexdigest()
-            unique = base64.b64encode(b(rnd_hash), b('__'))[:6]
-            return '%(fldtype)s CONSTRAINT [CK_%(fldtype)s_pos_%(unique)s_%%(column)s] CHECK ([%%(column)s] >= 0)' % locals()
-        return super(DataTypesWrapper, self).__getitem__(item)
-
 class DatabaseCreation(BaseDatabaseCreation):
     # This dictionary maps Field objects to their associated MS SQL column
     # types, as strings. Column-type strings can contain format strings; they'll
     # be interpolated against the values of Field.__dict__ before being output.
     # If a column type is set to None, it won't be included in the output.
     #
-    # Any format strings starting with "qn_" are quoted before being used in the
-    # output (the "qn_" prefix is stripped before the lookup is performed.
-
-    data_types = DataTypesWrapper({
-        'AutoField':                    'int IDENTITY (1, 1)',
-        'BigAutoField':                 'bigint IDENTITY (1, 1)',
-        'BigIntegerField':              'bigint',
-        'BinaryField':                  'varbinary(max)',
-        'BooleanField':                 'bit',
-        'CharField':                    'nvarchar(%(max_length)s)',
-        'CommaSeparatedIntegerField':   'nvarchar(%(max_length)s)',
-        'DateField':                    'date',
-        'DateTimeField':                'datetime',
-        'DateTimeOffsetField':          'datetimeoffset',
-        'DecimalField':                 'decimal(%(max_digits)s, %(decimal_places)s)',
-        'FileField':                    'nvarchar(%(max_length)s)',
-        'FilePathField':                'nvarchar(%(max_length)s)',
-        'FloatField':                   'double precision',
-        'GenericIPAddressField':        'nvarchar(39)',
-        'IntegerField':                 'int',
-        'IPAddressField':               'nvarchar(15)',
-        'LegacyDateField':              'datetime',
-        'LegacyDateTimeField':          'datetime',
-        'LegacyTimeField':              'time',
-        'NewDateField':                 'date',
-        'NewDateTimeField':             'datetime2',
-        'NewTimeField':                 'time',
-        'NullBooleanField':             'bit',
-        'OneToOneField':                'int',
-        'PositiveIntegerField':         'int CHECK ([%(column)s] >= 0)',
-        'PositiveSmallIntegerField':    'smallint CHECK ([%(column)s] >= 0)',
-        'SlugField':                    'nvarchar(%(max_length)s)',
-        'SmallIntegerField':            'smallint',
-        'TextField':                    'nvarchar(max)',
-        'TimeField':                    'time',        
-    })
+    
 
     def _create_test_db(self, verbosity, autoclobber):
         settings_dict = self.connection.settings_dict

**Comment by RossRogers** [comment]
Please put this into a pull request and document what it is doing?
