### ISSUE TITLE
Django 1.8.8 Migration Issues: No changes detected... and then Applying but no DB update

### ISSUE THREAD

**Issue by steve17767** [lionheart/django-pyodbc#107]
I believe these two are related.

I’m having two migration issues:

1.	I added a new file with two new classes (database tables).
2.	The tables are to be added to the local MySQL database (5.5).
3.     I have routers to other databases, but not the my local MySQL (developed under 1.5).
4.	I’m running Django 1.8.8 (recently updated from 1.6 via 1.7) and Pythoin 2.7.6.
5.	The first problem I had was that Django did not recognize  that I had added the new tables.
6.	I gave up on the new file (I have 6 other models_*.py files for this app that worked great under South) and just put the new classes in one of the existing files.
6.	Now makemigrations detected the changes and said it applied the changes.  But the new tables did not appear in the database.

#History#

##MY INITIAL MIGRATION (done during 1.7 upgrade):##

    $ ./manage.py makemigrations -v 3 sanity
    Migrations for 'sanity':
      0001_initial.py:
    - Create model Alert_User_Criteria
    - Create model Fail_Report_Branches
    - Create model Fail_Report_GPUs
    - Create model Fail_Report_OSes
    - Create model Fail_Report_Tests
    - Create model Failure_Branch_Summary
    - Create model Failure_GPU_Summary
    - Create model Failure_OS_Summary
    - Create model Failure_Test_Summary
    - Create model Failures
    - Create model Last_Vrl_Read
    - Create model Retry_Branch_Summary
    - Create model Retry_Detail
    - Create model Retry_GPU_Summary
    - Create model Retry_Summary
    - Create model Retry_Test_Summary
    - Create model Selectable_Code_Branch
    - Create model Selectable_Gpu
    - Create model Selectable_Os
    - Create model Selectable_Platform
    - Create model Selectable_Test_Name
    - Create model Special_Names
    - Create model Test_Machine

    sfuller@stevefullerubuntu:/opt/graphic_tools/gtools$ ./manage.py migrate -v 3 --fake sanity
    Operations to perform:
    Apply all migrations: sanity
    Running pre-migrate handlers for application admin 
    Running pre-migrate handlers for application auth
    Running pre-migrate handlers for application contenttypes
    Running pre-migrate handlers for application sessions
    Running pre-migrate handlers for application sites
    Running pre-migrate handlers for application registration
    Running pre-migrate handlers for application gtools
    Running pre-migrate handlers for application dashboard
    Running pre-migrate handlers for application restviewer
    Running pre-migrate handlers for application sanity
    Running pre-migrate handlers for application branch_health
    Running pre-migrate handlers for application staff_status
    Running migrations:
      Rendering model states... DONE (0.296s)
      Applying sanity.0001_initial... FAKED (0.010s)
    Running post-migrate handlers for application admin
    Running post-migrate handlers for application auth
    Running post-migrate handlers for application contenttypes
    Running post-migrate handlers for application sessions
    Running post-migrate handlers for application sites
    Running post-migrate handlers for application registration
    Running post-migrate handlers for application gtools
    Running post-migrate handlers for application dashboard
    Running post-migrate handlers for application restviewer
    Running post-migrate handlers for application sanity
    Running post-migrate handlers for application branch_health
    Running post-migrate handlers for application staff_status

    …sanity/migrations/$ ls -al
    -rw-rw-r-- 1  21731 Jan 25 16:06 0001_initial.py
    -rw-rw-r-- 1   9953 Jan 25 16:06 0001_initial.pyc
    -rw-rw-r-- 1         0 Jan 14 12:14 __init__.py
    -rw-rw-r-- 1     142 Jan 25 16:06 __init__.pyc

    mysql> select * from  django_migrations;
    +----+---------------+---------------------------------------+---------------------+
    | id | app           | name                                  | applied             |
    + ----+---------------+---------------------------------------+---------------------+
    |  1 | contenttypes  | 0001_initial                          | 2016-01-12 11:56:34 |
    |  2 | auth          | 0001_initial                          | 2016-01-12 11:56:34 |
    |  3 | admin         | 0001_initial                          | 2016-01-12 11:56:34 |
     . . .
    | 30 | sanity        | 0001_initial                          | 2016-01-25 16:06:52 |
    +----+---------------+---------------------------------------+---------------------+

##NEW FILE: MODELS_SA.PY##

    from django.db   import models
    from django.conf import settings
    
    class Archive_Control(models.Model):
    config_name  = models.CharField(max_length=128, null=False, unique=True, db_index=True)
    is_active    = models.BooleanField(default=True)
    oldest_build = models.DateTimeField(auto_now_add=True)
    newest_build = models.DateTimeField(auto_now_add=True)
    archive_url  = models.CharField(max_length=128, null=True)
    
    def __unicode__(self):
        return self.config_name
    
    class Meta:
        app_label = 'sanity'
        ordering = ['config_name']
    
    class Build_Archives(models.Model):
    config         = models.ForeignKey(Archive_Control, db_index=True)
    gcid           = models.CharField(max_length=16, null=True)
    build_nbr      = models.CharField(max_length=16, null=True)
    build_url      = models.CharField(max_length=128, null=True)
    build_datetime = models.DateTimeField(null=True)
    
    def __unicode__(self):
        return self.config+" : "+str(self.build_datetime)
    
    class Meta:
        app_label = 'sanity'
        ordering = ['build_datetime']
        get_latest_by = 'build_datetime'
    
    def get_sortable_build_datetime(self):
        return self.build_datetime.strftime("%Y%m%d%H%M%S")
    def get_formatted_build_datetime(self):
        return self.build_datetime.strftime("%Y-%m-%d %H:%M:%S")
    
    build_datetime_sortable  = property(get_sortable_build_datetime)
    build_datetime_formatted = property(get_formatted_build_datetime)

##RUN MAKEMIGRATIONS WITH NEW FILE##

    $ ./manage.py makemigrations -v 3 sanity
    No changes detected in app 'sanity'

##ADDED CONTENTS OF MODELS_SA.PY TO MODELS.PY##

    $ ./manage.py makemigrations -v 3 sanity
    Migrations for 'sanity':
      0002_archive_control_build_archives.py:
       - Create model Archive_Control
       - Create model Build_Archives

###Why did it work now?###

    $ ./manage.py migrate -v 3 sanity
    Operations to perform:
      Apply all migrations: sanity
    Running pre-migrate handlers for application admin
    . . .
    Running migrations:
      Rendering model states... DONE (0.275s)
      Applying sanity.0002_archive_control_build_archives... OK (0.072s)
    Running post-migrate handlers for application admin
    ...
    Running post-migrate handlers for application staff_status

    …/sanity/migrations$ ls -al
    total 64
    -rw-rw-r-- 1  21731 Jan 25 16:06 0001_initial.py
    -rw-rw-r-- 1    9953 Jan 25 16:06 0001_initial.pyc
    -rw-rw-r-- 1    1669 Jan 25 16:11 0002_archive_control_build_archives.py
    -rw-rw-r-- 1    1673 Jan 25 16:12 0002_archive_control_build_archives.pyc
    -rw-rw-r-- 1          0 Jan 14 12:14 __init__.py
    -rw-rw-r-- 1      142 Jan 25 16:06 __init__.pyc

    .../sanity/migrations$ cat 0002_archive_control_build_archives.py
    # -*- coding: utf-8 -*-
    from __future__ import unicode_literals
    
    from django.db import migrations, models
    
    class Migration(migrations.Migration):
    
    dependencies = [
        ('sanity', '0001_initial'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Archive_Control',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('config_name', models.CharField(unique=True, max_length=128, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('oldest_build', models.DateTimeField(auto_now_add=True)),
                ('newest_build', models.DateTimeField(auto_now_add=True)),
                ('archive_url', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['config_name'],
            },
        ),
        migrations.CreateModel(
            name='Build_Archives',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gcid', models.CharField(max_length=16, null=True)),
                ('build_nbr', models.CharField(max_length=16, null=True)),
                ('build_url', models.CharField(max_length=128, null=True)),
                ('build_datetime', models.DateTimeField(null=True)),
                ('config', models.ForeignKey(to='sanity.Archive_Control')),
            ],
            options={
                'ordering': ['build_datetime'],
                'get_latest_by': 'build_datetime',
            },
        ),
    ]

    mysql> select * from  django_migrations;
    +----+---------------+---------------------------------------+---------------------+
    | id | app           | name                                  | applied             |
    +----+---------------+---------------------------------------+---------------------+
    . . .
    | 30 | sanity        | 0001_initial                          | 2016-01-25 16:06:52 |
    | 31 | sanity        | 0002_archive_control_build_archives   | 2016-01-25 16:12:17 |
    +----+---------------+---------------------------------------+---------------------+

TABLES ARE NOT IN THE DATABASE!

**Comment by jieter** [comment]
Unfortunately, the maintenance for this lib is lagging considerably, nobody seems to be actively involved in supporting newer Django versions. I would not use it in the current state for any production environment.

Do you have to use mysql via OBDC? Why not connect to it using the standard Django way?
