### ISSUE TITLE
Django 1.9 is unsupported

### ISSUE THREAD

**Issue by Alexkane** [lionheart/django-pyodbc#109]
`File "/usr/local/lib/python2.7/dist-packages/django_pyodbc/base.py", line 52, in <module>
    raise ImproperlyConfigured("Django %d.%d is not supported." % DjangoVersion[:2])
django.core.exceptions.ImproperlyConfigured: Django 1.9 is not supported.`

**Comment by hellpain** [comment]
Please add support for django 1.9

**Comment by nichcz** [comment]
+1

**Comment by codyc4321** [comment]
this must be fixed, new source:

if DjangoVersion[:2] == (1, 9):
    _DJANGO_VERSION = 19

**Comment by drakej** [comment]
That change just allows the driver to operate on a project that is versioned at 1.9. It does not mean that the driver itself is fully compatible with Django 1.9

**Comment by keepryt** [comment]
I'm using Python 3.4 and Django 1.9 and get a similar error message:
  File "/home/rvm/django-user/lib/python3.4/site-packages/django_pyodbc/base.py", line 52, in <module>
    raise ImproperlyConfigured("Django %d.%d is not supported." % DjangoVersion[:2])
django.core.exceptions.ImproperlyConfigured: Django 1.9 is not supported

**Comment by codyc4321** [comment]
The update i saw is on the current version. Check you have the recent
version

**Comment by keepryt** [comment]
I think I have the latest version. I originally installed it about 30 minutes ago via:
pip install django-pyodbc

which output:
Collecting django-pyodbc
  Downloading django-pyodbc-0.3.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyodbc<3.1,>=3.0.6 in /home/rvm/django-user/lib/python3.4/site-packages/pyodbc-3.0.10-py3.4-linux-x86_64.egg (from django-pyodbc)
Building wheels for collected packages: django-pyodbc
  Running setup.py bdist_wheel for django-pyodbc ... done
  Stored in directory: /home/rvm/.cache/pip/wheels/64/dc/b8/1809bf7c8b24b454db9c2e112b090c76e51d2789bef528e8f7
Successfully built django-pyodbc
Installing collected packages: django-pyodbc
Successfully installed django-pyodbc-0.3.0

I just tried:
pip install django-pyodbc --upgrade

which output:
Requirement already up-to-date: django-pyodbc in /home/rvm/django-user/lib/python3.4/site-packages
Requirement already up-to-date: pyodbc<3.1,>=3.0.6 in /home/rvm/django-user/lib/python3.4/site-packages/pyodbc-3.0.10-py3.4-linux-x86_64.egg (from django-pyodbc)

**Comment by hack-r** [comment]
I also have this problem.

pyodbc was (finally) working with my Django 1.9.3 then some tutorial tricked me into using pip install with the -U flag, which automatically uninstalled Django 1.9.3 and installed 1.10. After uninstalling 1.10 and reinstalling 1.9.3 I get this 

Django 1.9.3 is not supported error when I try to run my web app

**Comment by RossRogers** [comment]
What is your django-pyodbc version?  `pip freeze |grep django-pyodbc`

**Comment by hack-r** [comment]
@RossRogers  Sorry please disregard my (now deleted) comment. When I went back to 1.9 I mis-remembered which version of 1.9 it was. Installing the right sub-version did the trick.

**Comment by RossRogers** [comment]
Ah.

**Comment by RossRogers** [comment]
As of right now, I'd like to suggest testing and working with alpha release 2.0.0a1 and using Django 2.0. I am closing this issue, but if this is an unacceptable outcome, please re-open the ticket. If you require Django 1.9 support then please feel free to re-open this ticket. Unfortunately, it is likely to remain unresolved, as there may not be any takers. Apologies.

**Comment by hack-r** [comment]
This is why there was no Windows 9. It's unlucky.
