### ISSUE TITLE
Django 1.10 unsupported

### ISSUE THREAD

**Issue by ofalk** [lionheart/django-pyodbc#119]
Hi!

As quick-fix - treat 1.10.x the same way as 1.9:

    if DjangoVersion[:2] == (1, 10):
        _DJANGO_VERSION = 19
    elif DjangoVersion[:2] == (1, 9):
        _DJANGO_VERSION = 19
    elif DjangoVersion[:2] == (1, 8):
        _DJANGO_VERSION = 18
    elif DjangoVersion[:2] == (1, 7):
        _DJANGO_VERSION = 17
    elif DjangoVersion[:2] == (1, 6):
        _DJANGO_VERSION = 16
    elif DjangoVersion[:2] == (1, 5):
        _DJANGO_VERSION = 15
    elif DjangoVersion[:2] == (1, 4):
        _DJANGO_VERSION = 14
    elif DjangoVersion[:2] == (1, 3):
        _DJANGO_VERSION = 13
    elif DjangoVersion[:2] == (1, 2):
        _DJANGO_VERSION = 12
    else:
        raise ImproperlyConfigured("Django %d.%d is not supported." % DjangoVersion[:2])

**Comment by dlo** [comment]
I support this. 😀

Will you submit a PR?

**Comment by ofalk** [comment]
Sure thing. Here you go @dlo ! :-)
