### ISSUE TITLE
Query aliases are not being replaced completly

### ISSUE THREAD

**Issue by bloodywing** [lionheart/django-pyodbc#123]
I'm running a DB2 and for some reason some parts of the query aliases are not getting replaced.

My DB gets this query: SELECT {MYDB2.Example}.{id}, {MYDB2.Example}.{ARTNR} FROM {MYDB2.Example}

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/fen/PycharmProjects/wisainfo/env/local/lib/python2.7/site-packages/django_pyodbc/base.py", line 490, in execute
    raise utils.DatabaseError(*e.args)
DatabaseError: ('42000', '[42000] [IBM][CLI Driver] CLI0118E  Invalid SQL syntax. SQLSTATE=37000 (-99999) (SQLExecDirectW)')`
```

My Model:

```
class Example(models.Model):
    artnr = models.TextField()
```

**Comment by RossRogers** [comment]
Hello Bloodywing,

In DB2, this is a valid query, if `MYDB2.Example` exists.
 
     SELECT {MYDB2.Example}.{id}, {MYDB2.Example}.{ARTNR} FROM {MYDB2.Example}

`{` and `}` are used for quoting in DB2 SQL.  Perhaps you haven't created the table or you don't have permissions?

This sequence of code works for me on my AS400 iSeries machine where `DOMEXQRY` is swapped `MYDB2`: 

    CREATE TABLE DOMEXQRY.Example (                                                                                                                                                                                                                                                                                                                                            
        id int,                                                                                                                                                                                                                                                                                                                                                                
        artnr varchar(255)                                                                                                                                                                                                                                                                                                                                                     
    )                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                           
    SELECT {DOMEXQRY.Example}.{id}, {DOMEXQRY.Example}.{ARTNR} FROM {DOMEXQRY.Example}                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                           
    drop table DOMEXQRY.Example


ODBC error 37000 is a syntax or an **access error**.  Do you have permissions?  Google ODBC 37000.

Closing ticket for now.  If you have more details that make it seem like it is django-pyodbc, please re-open.

**Comment by bloodywing** [comment]
I have read access to the Schema which I'm trying to access. I used the same credentials with python-ibmdb and the django module with it and it works there. The DB2 Version I'm testing with is DB2 LUW 10.5

I can check it tomorrow again at work if I missed something.

**Comment by RossRogers** [comment]
Can you use `{` and `}` as quotes in your version of DB2?

**Comment by RossRogers** [comment]
Good night! The combined documentation for IBM DB2 LUW 10.5 is 24,051 pages.

**Comment by bloodywing** [comment]
Nope, I picked the query today up and threw it right into my DB2 and DB2 told me the same syntax error. Then I simply removed the `{}` and the query works without problems. I researched a bit and there is something called xquery for db2 which uses xml lookup and it looks a bit similar, but I never saw something with the curly brackets before. My DB2 only accepts `"` for quoting.

:) Yup, IBMs docs are a mess.

**Comment by bloodywing** [comment]
Found this here: http://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzaik/odbcapis.htm and it says.

> SQL_IDENTIFIER_QUOTE_CHAR – By default a double-quote mark is returned. If the application in use is MS QUERY (MSQRY32) then a single blank is returned.

I can provide you more test results tomorrow, but I doubt that `[` will work.

**Comment by RossRogers** [comment]
I can access that configuration in pyodbc like:

    import pyodbc, os, sys
    driver_name = 'IBM i Access ODBC Driver'
    if os.name == 'nt':
        driver_name = 'iSeries Access ODBC Driver'
    connection = pyodbc.connect("CONNTYPE=2;DRIVER={%s};SYSTEM=10.0.0.2;UID=foo;PWD=bar"%driver_name)
        connection.getinfo(pyodbc.SQL_IDENTIFIER_QUOTE_CHAR)

However, doing so returns `"` for my as400 db2 setup, even though `"` doesn't work for me.  

I retrieved every variable accessible in pydobc's `getinfo` as defined on [this page](https://github.com/mkleehammer/pyodbc/blob/bc1eec863c5ab2ac6826f72be255661e01bac41e/src/pyodbcmodule.cpp#L786).  None of them have the text `{` even though my DB2 requires it.

I think we can't depend on the `SQLGetInfo` or `getinfo` results.

Thus, our best be is is probably to find the info in the `SYSIBM` meta tables.

**Comment by RossRogers** [comment]
Well, I can't figure out how to query `SYSIBM.*` or find the correct variable.  I'm really not good with DB2.  I put in the DB2 support, but it is really AS400 DB2.  Anyways, I'd prefer to trigger correct quoting based on a feature or a configuration setting.  Do you know which table or system variable would hold the information  about what kind of quoting the DB2 SQL parser uses?

**Comment by bloodywing** [comment]
Nope I started with DB2 yesterday. But I can ask my colleague tomorrow if he knows more about escaping. I saw so many example queries now and couldn't find a single one with `{`

Btw. you don't need to pull your hairs out on this, since I've got it running with another db engine for django.

**Comment by RossRogers** [comment]
IBM seems to have two products called DB2...  I happen to use the one that is less frequently used.  Anyways, if your colleague knows a trick then great.  Otherwise we should be able to add an explicit configuration option that allows non-AS400 DB2 users to manually specify the left-quote and right-quote, whether you use it our not :-)

**Comment by bloodywing** [comment]
IBM has a whole armada of products called DB2. And various query extensions that work in some versions and some version wont have them or they need to be activated first (I really have no idea, there is a reason why they offer paid support). I'll check out db2 express this weekend when I'm bored, maybe I can find a proper solution and even be able to detect the used escape char.

**Comment by RossRogers** [comment]
Yeah, I kinda recommend leaving off DB2, if you're somehow able to do so.
