### ISSUE TITLE
Edit Mac Setup Wiki

### ISSUE THREAD

**Issue by connorbode** [lionheart/django-pyodbc#130]
The wiki says we need to replace some lines in pyodbc, however, the latest version of pyodbc has the changes already made.  No need to download the tarball and edit.  (I'm referring to [this doc](https://github.com/lionheart/django-pyodbc/wiki/Mac-setup-to-connect-to-a-MS-SQL-Server))

> Go to PyPi and download pyodbc tarball and uncompress it. Then change these lines in setup.py:
> 
> elif sys.platform == 'darwin':
>         # OS/X now ships with iODBC.
>         settings['libraries'].append('iodbc')
> to:
> 
> elif sys.platform == 'darwin':
>         # OS/X now ships with iODBC.
>         settings['libraries'].append('odbc')

**Comment by RossRogers** [comment]
How do you suggest it be edited? I don't have a mac to test anything. Can you just use `pip` now?  Anyways, give me the full edits and I'll slap it right in there.

**Comment by connorbode** [comment]
Yes, the edits mentioned are now installed via `pip install pyodbc`; that whole section can be replaced by`pip install pyodbc`.

**Comment by RossRogers** [comment]
[That look right?](https://github.com/lionheart/django-pyodbc/wiki/Mac-setup-to-connect-to-a-MS-SQL-Server)

**Comment by connorbode** [comment]
That’s what worked for me!  Thanks for making the edit.  Will get back to your comment re: django 1.7 and django-pyodbc later today.

**Comment by RossRogers** [comment]
Thanks Connor.
