### ISSUE TITLE
Mac setup to connect to a MS SQL Server

### ISSUE THREAD

**Issue by sureshr207** [lionheart/django-pyodbc#134]
Your wiki page - Mac setup to connect to a MS SQL Server works perfectly fine for IPV4 connections which is based on tsql -S myserver(IPV4 address - XXX.XXX.XXX.XXX) -U myuser -P mypassword.

But it doesnt work on connecting with specific IPV6 address where I used tsql -S myserver(IPV6 address - XXXX:XXXX:X:X::X:XXXX or http://[XXXX:XXXX:X:X::X]:XXXX) -U myuser -P mypassword.

Is there something which I need to do or am I missing something?

**Comment by RossRogers** [comment]
Hi Suresh,

If you have a `tsql` question, you're going to want to post that question elsewhere.  Perhaps a `tsql` forum.
