### ISSUE TITLE
django-pyodbc and DBISAM ODBC driver

### ISSUE THREAD

**Issue by lanec** [lionheart/django-pyodbc#136]
I am working to get a Django project to talk with a DBISAM 4.21 database using the pyodbc and django-pyodbc software and can find little to nothing about how to make this work. It seems to me that DBISAM is a relatively obscure proprietary database server software based on SQL-92 standards. It is not listed as supported by pyodbc at this time but after opening an issue with them in their Git repo I'm able to initiate a connection with a DSN from within the Python shell:

`pyodbc.connect(r'DSN=DSNname;UID=User;PWD=Password’)`

The company that makes the software (Elevate Software) claims on their website that they support connections from non Delphi based projects using their provided ODBC driver (http://www.elevatesoft.com/products?action=order&category=dbisam&type=other).

I'm trying to use the DBISAM 4.21 database because I am working on interfacing an existing software written in Delphi that stores it's data in the DBISAM database with a new Python 3 + Django 1.10 based software that is yet to be written.

We have a test environment with Windows 2012 R2 running the DBISAM server software. It has the ODBC driver from the vendor installed along with the vendors Delphi based application. We have also loaded Python 3.6 along with Django 1.10.5 so we can try and get a connection working.

I am completely new to the world of DBISAM database technology AND completely new to the Python ODBC world so let me know if I can offer more details on anything to help the process.

When I load the following configuration into my settings.py file in Django as such:

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django_pyodbc',
        'DSN': 'DSNname',
        'USER': 'username',
        'PASSWORD': 'password',
        'NAME': 'databasename',
        'OPTIONS': {
            'host_is_server': True
            },
    }
}

I get the following output

`pyodbc.Error: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect)')`

I am wondering if anyone could offer any thoughts to help me get this connected?

**Comment by RossRogers** [comment]
Hi Lanec,
This is a general pyodbc issue.  You need to iterate on your parameters until it works like:

    import pyodbc
    connection = pyodbc.connect("CONNTYPE=2;DRIVER={IBM i Access ODBC Driver};SYSTEM=192.168.1.42;UID=foo;PWD=bar")
    print connection.cursor().execute("select 1 from baz_table")

It sure looks like your parameters are wrong. It rejected your request or it couldn't find the server.

Closing issue.  Not a django-pyodbc issue, but feel free to comment as we may have help.  I personally adapted django-pyodbc to IBM db2, so I know about obscure, redheaded step-children databases.

**Comment by lanec** [comment]
Hi Ross, 

Any help is appreciated with troubleshooting this.  I'm new to ODBC connections so not sure where to start and not finding much on Google.

Found this page that talks about the built in tests to pyodbc - http://www.easysoft.com/developer/languages/python/pyodbc.html but doesn't offer much insight into what a successful test looks like.  I'm able to run the script in that sites example as follows: 
`python tests3/sqlservertests.py DSN=DSNname`

It just completes and outputs nothing.

**Comment by RossRogers** [comment]
Take a look at my tiny little pyodbc snippet.   Under the hood, something like that happens for django-pyodbc to talk to pyodbc.  If you put my snippet into a file and keep iterating on it until you can get some sort of response from your glorious antique database ( :-D ), then we can help you translate that into a django configuration.

**Comment by lanec** [comment]
Ross, is there a sample of a response you can share so I know what I'm looking for?  

Do you know if there is any log to see what it's getting when it outputs nothing?

**Comment by RossRogers** [comment]
My particular example should printout:
    
    <pyodbc.Cursor object  at 0x7ffdeadbeef>

But what it _shouldn't_ do is print out the error:

    pyodbc.Error: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect)')

That is probably an exception.

**Comment by lanec** [comment]
Thanks!  That's helpful.  Does pyodbc always require a host/ip/system or can a DSN be enough?

**Comment by RossRogers** [comment]
It doesn't require an IP.  You can use a DSN, but then you have to make sure your DSN is configured correctly on windows https://www.google.com/#q=create+an+odbc+dsn+on+windows

When I look at your configuration, I see `DSNname` as the DSN's name.  What did you configure as your DSN name?  You had to set it when you created your DSN on your windows machine.

**Comment by lanec** [comment]
I swapped the DSN name I chose out with "DSNname" out of habit to obscure sensitive information about the environment but the more I've learned I think its safe to share since it's local only.  

The real DSN name is "channergy" and as it is the name of the software that created the database I'm looking to interface with (http://www.channergy.com).

**Comment by RossRogers** [comment]
Oh ok.  Well, that error sure looks like it is saying that either;
  * your windows DSN configuration isn't pointing to the correct IP or domain name ( `ping foo.bar.baz.com` it on the command line)
 * or you don't have the correct username and password

**Comment by lanec** [comment]
Okay, I don't have anything for the IP or domain in the DSN config.  It's just setup inside of the same Windows server that I'm trying to connect to under the DSN of Channergy: http://clicky.strapr.com/1z2L2v2P0g0l

**Comment by RossRogers** [comment]
You gotta make sure that DSN is configured correctly and that the username and password are legit.

**Comment by lanec** [comment]
Okay

**Comment by lanec** [comment]
Any thoughts on how to test if a DSN is configured correctly if not through pyodbc?

**Comment by RossRogers** [comment]
It's been years since I did my configuration.  You gotta do some more googling.

**Comment by lanec** [comment]
Okay thanks so much for the head start!

**Comment by venezianluis** [comment]
@lanec  were you able to connect and retrieve data from DBISAM using PyODBC? Could you show the code?

**Comment by lanec** [comment]
I was able to make it work but this was years ago and I didn't save the code. 

It took me about four days of effort to figure out how to do it if I recall correctly.

**Comment by lanec** [comment]
@venezianluis instead of messing with this you might be better off using a conversion tool. We had a DBISAM database (Borland Database Engine / SQL-92 / Elevatesoft) that was easily convertible to CSV using this tool: http://www.scalabium.com/dbisam/

I ended up going that route despite getting the database talking to Django with the PyODBC driver. I figured it was better to create new models anyway and easier to pull the data into the new models from CSV than trying to work off the antique database tech we were interfacing with.

**Comment by venezianluis** [comment]
@lanec, Thank you in advance for you time! 
I took a look at Scalabium tool and seems that it fits with my needed, which is extracting data to our Data Lake, i'm just searching right now to undestand if there's a CLI option for the usage of the tool since i need to create some flows to work in a CRON schedule.

**Comment by lanec** [comment]
I don’t think it has CLI support. Probably faster and easier to use robotic process automation to create an API that can control the windows interface.

**Comment by by2022done** [comment]
Hello there, it took me a couple of days to find out how all works with dbisam, I can share code if you would like, but the thing that I have a problem is reading blob from database. I will post simple crud if you are interested. I did all with pyodbc, but I just found with chatGPT out that there is also other library pydbisam. 

http://www.scalabium.com/dbisam/ is good one, but it can only read, not write as I can see. So with pyodbc you can make simple CRUD.
