### ISSUE TITLE
Using django-pyodbc with msodbcsq (on MacOS)

### ISSUE THREAD

**Issue by alokshenoy** [lionheart/django-pyodbc#137]
I am trying to use django-pyodbc with the latest preview version of msodbcsql (https://blogs.msdn.microsoft.com/sqlnativeclient/2017/02/03/odbc-driver-13-1-for-mac-preview-1-released/) on Sierra. 

In the settings.py, I have the following lines:
```
DATABASES = {
    'default': {
        'NAME': 'mydatabase',
        'ENGINE': 'django_pyodbc',
        'USER': 'djangotest',
        'PASSWORD': 'test_password_password',
        'OPTIONS':{
            'DRIVER': 'ODBC Driver 13 for SQL Server',
            'DSN': 'myserver',
            'AUTOCOMMIT': True,
        }
    }
}
```

My .odbc.ini (in ~ directory) looks like this:
```
[myserver]
Driver = ODBC Driver 13 for SQL Server
Server = tcp:myserver.com,20202
Database = mydatabase
Encrypt = YES
TrustServerCertificate = YES

```
My /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini (installed using home-brew) looks like this:

```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
UsageCount=1
```

Yet when I try `python manager.py migrate` I get the error: `pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'FreeTDS' : file not found (0) (SQLDriverConnect)")
`

It's still trying to use freeTDS. 

In a script (not inside django), I'm able to connect to the database using pyodbc (and the DNS name). Is there a way to force django-pyodbc to use msodbcsql?

**Comment by AkshayGuleria** [comment]
Try removing 'DRIVER' from database OPTIONS. The DSN knows about the DRIVER.
Just a casual suggestion to see if this might work since it worked in my case.

**Comment by rhare** [comment]
For those who are searching for a solution to this issue like I was:

'DRIVER' should be lowercase and not uppercase. The 'Configuration' section in the README clearly shows that the keys in the 'OPTIONS' value should be lowercase.

**Comment by RossRogers** [comment]
This does not appear to be a django-pyodbc specific issue, although django-pyodbc does depend on proper pyodbc operation.  Please see our [README][https://github.com/lionheart/django-pyodbc#installation], bullet point 3 on resources to debug your pyodbc connection. Closing.
