### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Django 1.11 is not supported.

### ISSUE THREAD

**Issue by javierhuerta** [lionheart/django-pyodbc#142]
Please, add support for Django 1.11

**Comment by RossRogers** [comment]
As of right now, I'd like to suggest testing and working with alpha release 2.0.0a1 and using Django 2.0. I am closing this issue, but if this is an unacceptable outcome, please re-open the ticket. If you require Django 1.11 support then please feel free to re-open this ticket. Unfortunately, it is likely to remain unresolved, as there may not be any takers. Apologies.

**Comment by Xeizzen** [comment]
Hello Ross Rogers.
I don't know if this is possible at this point, but right now we can't migrate to Django 2.x.x since we're stuck at python 2.7, therefore we would really appreciate if you'll add the support for 1.11 Django.

**Comment by RossRogers** [comment]
@Xeizzen,

Can I ask you what is preventing you from migrating to 2.7 on your project using django-pyodbc only?  If you use virtualenv, you can isolate the app from other python 2.7 projects.  

If that isn't an option, how about running 3to2 against the Django 2 branch and getting it to work with 1.11?

As of right now, I'm incredibly swamped by my real life to take on enabling 1.11.  

- Ross

**Comment by Xeizzen** [comment]
Sure Ross, do not bother then.
We simply removed some connections with old database that uses pyodbc.
Everything is working now.
