### ISSUE TITLE
Please update for Django 1.11.1

### ISSUE THREAD

**Issue by hakanw** [lionheart/django-pyodbc#147]
Hey,

Would be great if this package would be compatible with the latest version of Django (right now at 1.11.1)

Thanks!

**Comment by bartmika** [comment]
Hey guys, just wondering what the status is of this ticket?

**Comment by Meloncon** [comment]
Hey team, I'm looking to start a new Django 1.11.4 project and am also wondering when this package will be updated. Thanks for all the hard work! :)

**Comment by shadiakiki1986** [comment]
Just my 2 cents: I've been using [michiya/django-pyodbc-azure](https://github.com/michiya/django-pyodbc-azure) for odbc on Sql Server, but I also just filed michiya/django-pyodbc-azure#125 asking whether that project is still maintained. Also, in [this SO answer](https://stackoverflow.com/a/47029373/4126114) I tried to summarize the current status of django with odbc/sql server, but it seems like a dead end ATM

**Comment by dlo** [comment]
See #151. We just need tests for that PR and we’re good to go on 1.11.

**Comment by RossRogers** [comment]
As of right now, I'd like to suggest testing and working with alpha release 2.0.0a1 and using Django 2.0.  I am closing this issue, but if this is an unacceptable outcome, please re-open the ticket.
