### ISSUE TITLE
SchemaEditor error

### ISSUE THREAD

**Issue by thomgonzalez** [lionheart/django-pyodbc#150]
I have problems in database migration, as I can solve this error.
I requirements:
Python 3.5
Django 1.8
Pyodbc 3.0.7
django-pyodbc 1.1.0

Error:
'The SchemaEditorClass attribute of this database wrapper is still None')
NotImplementedError: The SchemaEditorClass attribute of this database wrapper is still None

**Comment by timgraham** [comment]
Duplicate of https://github.com/lionheart/django-pyodbc/issues/110.
