### ISSUE TITLE
Using for dbf files

### ISSUE THREAD

**Issue by Arlington1985** [lionheart/django-pyodbc#153]
In documentation written that can connect to MS SQL Server. Is it possible to configure for CRUD operations in dbf ?

**Comment by RossRogers** [comment]
django-pyodbc connects through a module called pyodbc. Your dbf needs to have a proper pyodbc connection.  Then, you can tweak the settings, including `left_sql_quote`, and `right_sql_quote` to give it a try.  I go django-pydobc working with IBM DB2, so it could work.  Not sure, however.
