### ISSUE TITLE
Different schemas in models.py

### ISSUE THREAD

**Issue by angelqb17** [lionheart/django-pyodbc#165]
How can i detect the schema for the models? because right know i am having this error:

py", line 221, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'temptrhist' models in application 'inflacion': <class
 'inflacion.models.TemptrHist'> and <class 'inflacion.models.Temptrhist'>.

this are the classes:

class TemptrHist(models.Model):
    tr_part = models.TextField(blank=True, null=True)
    tr_type = models.TextField(blank=True, null=True)
    tr_loc = models.TextField(blank=True, null=True)
    tr_qty_req = models.DecimalField(max_digits=38, decimal_places=10, blank=True, null=True)
    tr_qty_chg = models.DecimalField(max_digits=38, decimal_places=10, blank=True, null=True)
    tr_qty_short = models.DecimalField(max_digits=38, decimal_places=10, blank=True, null=True)
    tr_nbr = models.TextField(blank=True, null=True)
    tr_rmks = models.TextField(blank=True, null=True)
    tr_lot = models.TextField(blank=True, null=True)
    tr_serial = models.TextField(blank=True, null=True)
    tr_effdate = models.TextField(blank=True, null=True)
    tr_domain = models.TextField(blank=True, null=True)
    oid_tr_hist = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'temptr_hist'

class Temptrhist(models.Model):
    vcfactura = models.TextField(db_column='vcFactura', blank=True, null=True)  # Field name made lowercase.
    ipartida = models.TextField(db_column='iPartida', blank=True, null=True)  # Field name made lowercase.
    vcproducto = models.TextField(db_column='vcProducto', blank=True, null=True)  # Field name made lowercase.
    vcserial = models.TextField(db_column='vcSerial', blank=True, null=True)  # Field name made lowercase.
    vctipo = models.TextField(db_column='vcTipo', blank=True, null=True)  # Field name made lowercase.
    vcdominio = models.TextField(db_column='vcDominio', blank=True, null=True)  # Field name made lowercase.
    dtfechaeff = models.CharField(db_column='dtFechaEff', max_length=10, blank=True, null=True)  # Field name made lowercase.
    itrnbr = models.IntegerField(db_column='iTrNbr', blank=True, null=True)  # Field name made lowercase.
    vctrrmks = models.TextField(db_column='vcTrRmks', blank=True, null=True)  # Field name made lowercase.
    vcnbr = models.TextField(db_column='vcNbr', blank=True, null=True)  # Field name made lowercase.
    vccliente = models.TextField(db_column='vcCliente', blank=True, null=True)  # Field name made lowercase.
    mqtychg = models.DecimalField(db_column='mQtyChg', max_digits=19, decimal_places=4, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'temptrhist'

**Comment by RossRogers** [comment]
I believe this is a core Django restriction.  You need to name those two table models differently other than just changing the letter casing.

I'd recommend renaming both of those models to say what they actually do.  They're clearly very similar, but for long term maintenance, you'd want to have meaningful names.
