### ISSUE TITLE
Help in setting up connection with load balancer

### ISSUE THREAD

**Issue by aravchr** [lionheart/django-pyodbc#168]
Hi

Can you guys please help in setting up connection with load balancer ? where the primary & secondary are separate but using a single host? 

Thanks
Aravind

**Comment by RossRogers** [comment]
Load balancing is not really specific to django-pyodbc, but more django.  Take a look at https://tech.marksblogg.com/load-balancing-django.html and https://stackoverflow.com/questions/48677643/load-balancing-in-django
