### ISSUE TITLE
iODBC "DRIVER" support

### ISSUE THREAD

**Issue by neilobremski** [lionheart/django-pyodbc#25]
iODBC (installed by default on OS X) cannot load drivers specified by name in curly braces, i.e. {FreeTDS} ( see: http://www.iodbc.org/dataspace/iodbc/wiki/iODBC/FAQ ) . You can, however, specify the path to the driver file and so Driver={FreeTDS} becomes Driver=/usr/local/lib/libtdsodbc.so .

Note that there are no curly braces in this format and thus the bug/missing-feature I've found is that django-pyodbc always adds curly braces. The second part of this problem is that it does a string match on the driver name to see if it's FreeTDS.

The two code changes I propose (to base.py) for remedy: First, look for path separator chars in the driver string and, if they appear, use the value without curly braces. And secondly to make a flag (isFreeTDS?) that is set if the driver value equals "FreeTDS" or ends with "/libtdsodbc.so". This flag would then be used instead of driver == "FreeTDS".

Thoughts?

**Comment by RossRogers** [comment]
Per @tax comment, closing.
