### ISSUE TITLE
Data source name not found, and no default driver specified

### ISSUE THREAD

**Issue by dan-klasson** [lionheart/django-pyodbc#46]
I'm using Ubuntu 12.04 server, Django 1.5.5, pyodbc-3.0.7 and I am trying to connect to a MSSQL 2005 server. I've installed django-pyodbc through pip and modified my settings.py like so:

```
 DATABASES = {
    'default': {
        'ENGINE': 'django_pyodbc', 
        'NAME': 'db_name',                     
        'USER': 'user_name',                    
        'PASSWORD': 'password',              
        'HOST': 'AB131\A_INS01',                  
        'PORT': '',                    
        'OPTIONS': {
           'host_is_server': True
        },
    }
}
```

But when I try to run syncdb I get:

```
 Error: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
```

The ODBC driver installed on the Windows machine is:

```
  SQL Server 6.01.7601.17514 SQLSRV32.DLL
```

What else do I need to do? Are there any other drivers that I need to install on either the Linux or Windows machine?

**Comment by RossRogers** [comment]
This is a pyodbc-> server issue.  Closing.

**Comment by AliSajah** [comment]
Ross Roger.
I am having the same problem.How do mean its a pyodbc problem?
For me i am working on a django project on windows 10 which am trying to connect to SQL SERVER .
Below are my setting please help?

But im getting  the following errors
DATABASES = {

'default': {
'ENGINE': "sql_server.pyodbc",
'HOST': "127.0.0.1",
'PORT': '1433',
'USER': "student",
'PASSWORD': "XXXXXXX",
'NAME': "database_name",

    }
}


  File "C:\Python36\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python36\lib\site-packages\sql_server\pyodbc\base.py", line 307, in get_new_connection
    timeout=timeout)
django.db.utils.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

**Comment by dlo** [comment]
@AliSajah Please ask this on StackOverflow and post question URL in a follow-up comment, since this isn't a django-pyodbc specific issue. Thanks!
