### ISSUE TITLE
Please add Sybase ASE support

### ISSUE THREAD

**Issue by saltduck** [lionheart/django-pyodbc#48]
I use Sybase ASE 11.9 and 12.5 via FreeTDS under linux. When I use django-pyodbc to execute any model query, it raise Exception at base.py line 289.

I think this is cause of lacking suppport for Sybase ASE. Please fix it.

**Comment by flavioelawi** [comment]
Is it trying to use the SERVERPOPERTY stored procedures? i think it needs that procedure in case it's a mssql db, but i need this library for sybase IQ and i cannot get it to work.

**Comment by RossRogers** [comment]
Compatible pull requests will be accepted, but we do not currently have plans or volunteers to take this on.  Closing.
