### ISSUE TITLE
Pytds

### ISSUE THREAD

**Issue by jordanorc** [lionheart/django-pyodbc#54]
Is there anyone working to use pytds (https://github.com/denisenkom/pytds) instead of pyodbc?

I made a simple modification into the code to use the pytds and everything seems to be ok (the tests are running).

I found another project by the same author (https://bitbucket.org/denisenkom/django-pytds) but is outdated.

There is interest in supporting this project pytds? As the pytds is an implementation in pure Python, you may want to bet on it.

**Comment by RossRogers** [comment]
Per last post, this feature is in the trunk.
