### ISSUE TITLE
Problem with django1.7, pyobdc on windows 7 

### ISSUE THREAD

**Issue by tsobeng** [lionheart/django-pyodbc#76]
I use django1.7 and pyobdc on windows 7 

when I try to connected to an MS Access DB, I have this error

raise NotImplementedError('subclasses of BaseDatabaseWrapper may require a schema_editor() method')
NotImplementedError: subclasses of BaseDatabaseWrapper may require a schema_editor() method

Thanks

**Comment by deumo** [comment]
I just got the same error on Ubuntu 12.04

**Comment by RossRogers** [comment]
I am using Django 1.7.10, [the latest version of django pyodbc on the trunk (e8b68a29) ](https://github.com/lionheart/django-pyodbc/commit/e8b68a29e265772878ec59d17b64c6f313112f70), pyodbc 3.0.7 and I am not seeing this.  I recall seeing this when I upgrade from 1.6 to 1.7, but I don'pt know how it was resolved.

Are you guys still seeing this?  If so, can you add the full stack trace?
