### ISSUE TITLE
problem with function _alias_columns

### ISSUE THREAD

**Issue by aginpatrick** [lionheart/django-pyodbc#79]
I use django1.6 and pyobdc on Ubuntu 14.04. In some circumstances, a TypeError is thrown from _alias_columns in compiler.py. The error is at line 341:
```text
parens[key] = buf% parens
```
The error is : "not enough arguments for format string"
The value of the sql variable in the function when it crashes is:
```text
[entites_entite].[id] FROM [entites_entite] WHERE ([entites_entite].[table_type] = %s  AND [entites_entite].[in_dico] = %s )
```
At the time execution hits the line 341, parens is still {} and the TypeError is thrown. 
What's the purpose of the function? Is it supposed to process the WHERE clause?
Thank you for the help,
Patrick

**Comment by aginpatrick** [comment]
@dlo Would it be possible to just tell me the purpose of the function _alias_columns and what is supposed to do with the WHERE clause? I have an urgent need here and I could try to path the code for my own use. Thank you very much!

**Comment by tcx9871** [comment]
I have similar problem ("The SQL contains 0 parameter markers, but 1 parameters were supplied" when trying to fetch second page datatable data), and replacing "parens[key] = buf% parens" with just "parens[key] = buf" fixes it.

**Comment by gmc-dev** [comment]
created a pull request https://github.com/lionheart/django-pyodbc/pull/81 that fixes this
