### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vanflymen** [lionheart/django-pyodbc#80]
Would it be possible to include more of a detailed installation procedure? 

Eg. FreeTDS, ODBC then django-pyodbc

Been having a hard time getting django-pyodbc to run with Django 1.7 on Ubuntu 14.04, not much documentation out there.

**Comment by tax** [comment]
Hi @vanflymen I think this might help you in setting up the driver (the MS linux driver in this case), https://github.com/tax/mssqldriver .

**Comment by vanflymen** [comment]
I'd love to buy you a beer for that. Thank you.
