### ISSUE TITLE
Django 1.8 compatibility?

### ISSUE THREAD

**Issue by jahrain** [lionheart/django-pyodbc#82]
Django 1.8 has many backwards incompatibility with database backends due to the new backend API. Is anyone working on this?

**Comment by dlo** [comment]
I'm not...if anyone wants to take a stab at it, I'll readily take pull requests. :)

**Comment by jieter** [comment]
Note that 1.7 is not really supported as well, at least no unit testing is done...

**Comment by jahrain** [comment]
Created a PR here: https://github.com/lionheart/django-pyodbc/pull/83

I agree about the unit test coverage though for 1.7. The fixes for the backend compatibility issues with 1.8 were rather simple just by adding some ImportError exception handling but I know 1.7 had much more drastic changes worthy of proper unit testing.

**Comment by jieter** [comment]
I think the fact that there is no coverage for 1.7 makes the need for unit tests for 1.8 even higher. I wouldn't use it in production this way...
