### ISSUE TITLE
Error with raw SQL queries

### ISSUE THREAD

**Issue by tapia** [lionheart/django-pyodbc#88]
I'm using django-pyodbc to make some raw SQL queries, and I've seen an error when using a LIKE statement. If I make this query with a sqlserver client (tsql, for example), I get some valid results:

    SELECT * FROM [MYTABLE] WHERE [FIELD] LIKE '%27%'

But if I make the same query using django-pyodbc, I don't get any error, but the result is empty (and it shouldn't):

    cursor = connections['myDB'].cursor()
    sql = "SELECT * FROM [MYTABLE] WHERE [FIELD] LIKE '%27%'"
    cursor.execute(sql)
    rows = cursor.fetchall()
    print rows

Making some tests, the bug seems to happen when the LIKE statement contains just numbers. If I make the query with something like `LIKE '%7A%'`, the result is OK. It happens with `NCHAR` and `NVCHAR` fields.

**Comment by RossRogers** [comment]
Take a look at this StackOverflow answer to print the _exact_ SQL being sent to the server out to the console:  
http://stackoverflow.com/a/10155661/20712

Then, run Django with `python manage.py runserver [...]` and post the exact SQL string being sent to the server, please.

**Comment by RossRogers** [comment]
Hi Tapia,

Please re-open this ticket if it remains unresolved.  Closing.
