### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by chrisgogreen** [lionheart/django-pyodbc#97]
Start maintaining release tags and changelog.

**Comment by RossRogers** [comment]
If and when this is done, [Semantic Versioning](http://semver.org/) could be a good way to version releases.

**Comment by RossRogers** [comment]
Hi [Dan](@dlo),  

How does one make releases?  I imagine some magic must be done on pip as well?

**Comment by dlo** [comment]
I just bump the version in `django_pyodbc/metadata.py` and then run `make`.

Right now it's just associated with my PyPi account...send over your username and I'll add you in!

**Comment by RossRogers** [comment]
I now have an account as "RossRogers"

**Comment by dlo** [comment]
Great, just added.

**Comment by RossRogers** [comment]
This is now implemented.  v1.0.0 is release to PyPi and github.
