### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by backbohne** [lionheart/django-pyodbc#98]
Hi,
just noticed that Django versions support has been hard coded and 1.8 is not supported :-(

Not  sure what exactly has been changed in 1.8 but maybe this link will describe all changes:

https://docs.djangoproject.com/en/1.8/releases/1.8/#database-backend-api

After patching all related import module seems working fine.

**Comment by RossRogers** [comment]
[This merge](https://github.com/lionheart/django-pyodbc/commit/e8b68a29e265772878ec59d17b64c6f313112f70), done on 7/29/15, was an attempt to integrate 1.8 support.  I've been using it successfully.  Unfortunately, it hasn't been released to the `pip` system. 

@dlo,

Any chance you could pull the trigger and push out the trunk to pip system?

**Comment by dlo** [comment]
Thanks @RossRogers--I've just been slammed. Will push up a new pip release in a minute.

**Comment by dlo** [comment]
Alright, live as 0.3.0 :)

**Comment by dlo** [comment]
#82

**Comment by RossRogers** [comment]
Thanks Dan.

**Comment by backbohne** [comment]
Wow, thanks! Amazing speed ;-)
